sudo: required

language: cpp

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: xenial
      # https://docs.travis-ci.com/user/reference/xenial/
      sudo: required
      
    - os: osx
  allow_failures:
    - os: osx

compiler:
  - gcc
  - clang

#services:
#  - os: linux
#    docker 

before_install:
 - if [[ "`uname`" == "Linux" ]]; then docker pull ubuntu:16.04; fi

script:
 - if [[ "`uname`" == "Linux" ]]; then docker build .; fi


 
