sudo: required
language: cpp

# os:
#   - linux
#   - osx

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2

      
compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install boost; fi

script:
  - echo $PWD
  - sh scripts/buildAndRunTests.sh

# sudo: required

# language: cpp

# compiler:
#   - gcc
#   - clang

# services:
#   - docker 

# before_install:
#   - docker pull ubuntu:16.04 

# script:
#  - docker build .

#  