sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode7.2


compiler:
  - gcc
 # - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; echo uname -a; then brew update; brew install boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; echo uname -a; sh scripts/travis-bootstrap-ubuntu.sh; fi

script:
  - echo $PWD
  - sh scripts/buildAndRunTests.sh

# sudo: required

# language: cpp

# compiler:
#   - gcc
#   - clang

# services:
#   - docker 

# before_install:
#   - docker pull ubuntu:16.04 

# script:
#  - docker build .

#  