sudo: required

language: cpp

os:
  - linux
  - osx

dist:
  - trusty      
  
compiler:
  - gcc
  - clang

before_install:
 - if [[ "`uname`" == "Linux" ]]; then docker pull ubuntu:16.04; fi

 install:
  - if [[ "`uname`" == "Darwin" ]]; then brew install boost; fi

script:
 - if [[ "`uname`" == "Linux" ]]; then docker build .; fi
 - if [[ "`uname`" == "Darwin" ]]; sh scripts/buildAndRunTests.sh; fi


 
