name: cmake_build_run_ctest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Bootstrap
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}  
        gcc --version
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install ninja-build cmake gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
        sudo apt-get install -y unzip zlib1g-dev libboost-all-dev libc6-dev
        echo gcc version after
        gcc --version        
        cmake --version
    - name: build, and run ctest
      shell: bash
      run: ./scripts/buildAndRunTests.sh
