name: Windows CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: install g3log
      working-directory: ${{github.workspace}}
      run: | 
        git clone https://github.com/KjellKod/g3log.git  
        cd g3log
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCHANGE_G3LOG_DEBUG_TO_G3LOG_DEBUG=ON -DCMAKE_PREFIX_PATH=c:\Libraries -DADD_FATAL_EXAMPLE=OFF -DCMAKE_INSTALL_PREFIX=c:\Libraries -DG3_SHARED_LIB=OFF -DG3_SHARED_RUNTIME=ON  ..
        mkdir c:\\Libraries
        cmake --build . --target INSTALL --config Release
        cd .. 
        cd .. 
        mkdir build
        mkdir zlib

    - name: install zlib
      working-directory: ${{github.workspace}}/zlib
      run: |
        curl http://zlib.net/zlib-1.2.11.tar.gz -o zlib.tar.gz
        tar xvzf zlib.tar.gz
        cd zlib-1.2.11/
        mkdir build
        cd build 
        cmake -DCMAKE_PREFIX_PATH=c:\\Libraries -DCMAKE_INSTALL_PREFIX=c:\\Libraries ..
        cmake --build . --target INSTALL --config Release

    - name: Build g3Sinks and run tests
      # Build your program with the given configuration
      working-directory: ${{github.workspace}}/build
      run: |
          set PATH=c:\\Libraries\\bin;%PATH%
          cmake -DCMAKE_BUILD_TYPE=Release -DCHOICE_BUILD_STATIC=ON -DCMAKE_PREFIX_PATH=c:\Libraries -DCMAKE_INSTALL_PREFIX=c:\Libraries  ..
          cmake --build . --target INSTALL --config Release
          tree /A /F c:\g3log
          cpack -G "NSIS;ZIP"
          cpack -C Release
          ctest -V

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.  
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
      
